const orderList = [
  {
    id: "cs_test_b1nodBUjzByGPVOQwVqvCSLqZsTV81Mcr8cBA9lCoMGOIvZo3YADlwthGl",
    amount: 882.99,
    amountShipping: 10,
    images: [
      "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
      "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
      "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    ],
    timestamp: 1656722113,
    items: [
      {
        id: "li_1LGuGgLMk657ciumXCgqBVnr",
        object: "item",
        amount_subtotal: 69500,
        amount_total: 69500,
        currency: "cad",
        description:
          "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
        price: {
          id: "price_1LGuGgLMk657ciumqUJqmiyE",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721982,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_LyoIdXkYSxt6yF",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 69500,
          unit_amount_decimal: "69500",
        },
        quantity: 1,
      },
      {
        id: "li_1LGuGgLMk657ciumVgBxee8c",
        object: "item",
        amount_subtotal: 16800,
        amount_total: 16800,
        currency: "cad",
        description:
          "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
        price: {
          id: "price_1LGuGgLMk657ciumspH98F2l",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721982,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_Lys0tzK54d8x46",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 16800,
          unit_amount_decimal: "16800",
        },
        quantity: 1,
      },
      {
        id: "li_1LGuGgLMk657cium3bfc3j4f",
        object: "item",
        amount_subtotal: 999,
        amount_total: 999,
        currency: "cad",
        description:
          "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
        price: {
          id: "price_1LGuGgLMk657ciumUFrEUTxt",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721982,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_Lys0KcolKLNgqp",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 999,
          unit_amount_decimal: "999",
        },
        quantity: 1,
      },
    ],
  },
  {
    id: "cs_test_b1uzOYniIcYWYnitWzynJbRfDr1OoXFH4t5MKbEhcIK04kSQPfQu3hDtv3",
    amount: 40.79,
    amountShipping: 10,
    images: [
      "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
      "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
      "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    ],
    timestamp: 1656721571,
    items: [
      {
        id: "li_1LGu8yLMk657ciumt1lY4f2o",
        object: "item",
        amount_subtotal: 1299,
        amount_total: 1299,
        currency: "cad",
        description:
          "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
        price: {
          id: "price_1LGu8yLMk657ciumS1kKGSOG",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721503,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_LyrsjAgLNnQz3Z",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 1299,
          unit_amount_decimal: "1299",
        },
        quantity: 1,
      },
      {
        id: "li_1LGu8yLMk657cium00VAXAe4",
        object: "item",
        amount_subtotal: 795,
        amount_total: 795,
        currency: "cad",
        description:
          "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
        price: {
          id: "price_1LGu8yLMk657ciumdYzpIgwn",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721504,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_LyrslI5c06vVTW",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 795,
          unit_amount_decimal: "795",
        },
        quantity: 1,
      },
      {
        id: "li_1LGu8yLMk657ciumKAAKJ5D5",
        object: "item",
        amount_subtotal: 985,
        amount_total: 985,
        currency: "cad",
        description:
          "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
        price: {
          id: "price_1LGu8yLMk657ciumcYh3hTjc",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721504,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_LyrsR1Z7qrUdGd",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 985,
          unit_amount_decimal: "985",
        },
        quantity: 1,
      },
    ],
  },
  {
    id: "cs_test_b1G5ioZLvN49EPOahFtvWzPb1j9bBEph0Yur3PbKC5RkLD5SeKENxsbShp",
    amount: 198.24,
    amountShipping: 10,
    images: [
      "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
      "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
      "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    ],
    timestamp: 1656721348,
    items: [
      {
        id: "li_1LGu4pLMk657ciumv3OUNvCt",
        object: "item",
        amount_subtotal: 10995,
        amount_total: 10995,
        currency: "cad",
        description:
          "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
        price: {
          id: "price_1LGu4pLMk657cium4GkC1GlD",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721247,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_LyigVgvpOoVuMz",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 10995,
          unit_amount_decimal: "10995",
        },
        quantity: 1,
      },
      {
        id: "li_1LGu4pLMk657ciumNA3lrRqz",
        object: "item",
        amount_subtotal: 2230,
        amount_total: 2230,
        currency: "cad",
        description:
          "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        price: {
          id: "price_1LGu4pLMk657ciumBCYmqFAX",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721247,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_Lyigo0leZzrzMK",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 2230,
          unit_amount_decimal: "2230",
        },
        quantity: 1,
      },
      {
        id: "li_1LGu4qLMk657cium1Dph8Bbm",
        object: "item",
        amount_subtotal: 5599,
        amount_total: 5599,
        currency: "cad",
        description:
          "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
        price: {
          id: "price_1LGu4pLMk657ciumbGZuRXNB",
          object: "price",
          active: false,
          billing_scheme: "per_unit",
          created: 1656721247,
          currency: "cad",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_LyigCFyC99lzCu",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 5599,
          unit_amount_decimal: "5599",
        },
        quantity: 1,
      },
    ],
  },
];

export default orderList